name: "Export DSN"
description: "Export Specctra DSN from a Kicad PCB"
inputs:
  keyboard_dir:
    description: The parent directory of the Ergogen config.yaml
    required: true
    type: string
  boards:
    description: "KiCad PCB names"
    required: true
runs:
  using: "docker"
  #image: "docker://docker.io/kicad/kicad@sha256:5716d82aa247abdbe512650eb4e8fce5a4031cbbef0a2c8df83208a69fef87b2" # v8.0.9
  image: "docker://ghcr.io/inti-cmnb/kicad8_auto@sha256:bc23a40bdd1beeb0b15738df902c3c434fa8d6e89d34a1903b67952d004bdce6" # v1.9.1
  entrypoint: "/bin/bash"
  args:
    - "-c"
    - |
      cd ${{ inputs.keyboard_dir }}
      for board in ${{ inputs.boards }};
      do
        echo "Processing $board";
        if [ -e $GITHUB_WORKSPACE/pcbs/${board}.dsn ]; then
          echo "Cleaning up $GITHUB_WORKSPACE/pcbs/${board}.dsn";
          rm -f $GITHUB_WORKSPACE/pcbs/${board}.dsn;
        fi
        if [ -e pcbs/${board}.kicad_pcb ]; then
          echo "Export DSN";
          $GITHUB_WORKSPACE/kibot/export_dsn.py -b $GITHUB_WORKSPACE/pcbs/${board}.kicad_pcb -o $GITHUB_WORKSPACE/pcbs/${board}.dsn
        fi
      done
