name: Build

on:
  workflow_call:
    inputs:
      keyboard_name:
        description: Name of the keyboard
        required: true
        type: string
      keyboard_dir:
        description: The parent directory of the Ergogen config.yaml
        required: true
        type: string

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive

      - name: Use Node.js 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm install

      - name: Ergogen help
        run: npm run gen -- --help

      - name: Generate unrouted PCBs
        run: npm run gen -- "${{ inputs.keyboard_dir }}" -o "${{ inputs.keyboard_name }}"

      - name: Export DSN file for Freerouting
        uses: ./.github/actions/export-dsn
        with:
          boards: ${{ inputs.keyboard_name}}
          keyboard_dir: ${{ inputs.keyboard_dir }}

      - name: Autoroute main PCB
        uses: ./.github/actions/autoroute
        with:
          boards: ${{ inputs.keyboard_name }}
          keyboard_dir: ${{ inputs.keyboard_dir }}

      - name: Import SES into main PCB
        uses: ./.github/actions/import-ses
        with:
          boards: ${{ inputs.keyboard_name}}
          keyboard_dir: ${{ inputs.keyboard_dir }}

      - name: Export Gerbers for main PCB
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: ${{ inputs.keyboard_name }}/pcbs/${{ inputs.keyboard_name}}.kicad_pcb
          gerbers_dir: ${{ inputs.keyboard_name }}/gerbers

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "build: generate ${{ inputs.keyboard_name }} files"
          file_pattern: ${{ inputs.keyboard_name }}/
